[package]
name = "glyphrs"
version = "0.1.4"
edition = "2021"
license = "MIT"
description = "A text art generator written in Rust"

[dependencies]
clap = "4.5.4"
serde = { version = "1.0.203", features = ["derive"] }
toml = "0.8.13"
